version: 2

updates:
- package-ecosystem: 'github-actions'
  directory: '/'
  schedule:
    interval: 'daily'
  labels:
    - "skip changelog"
    - "dependencies"

- package-ecosystem: 'terraform'
  directory: '/modules/*/*.tf'
  schedule:
    interval: 'daily'
  labels:
    - "skip changelog"
    - "dependencies"