name: Module
on:
  pull_request:
    branches:
      - "main"
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"
    paths:
      - "modules/test/**"

defaults:
  run:
    shell: bash

env:
  TF_VERSION: 1.3.9
  TF_PLUGIN_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  TF_ROOT: ${{ github.workspace }}/modules/test

jobs:
  terraform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        terraform-versions: [latest]

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      
      - name: Setup Terraform - ${{ matrix['terraform-versions'] }}
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ matrix['terraform-versions'] }}

      - name: Terraform fmt - ${{ matrix['terraform-versions'] }}
        run: terraform fmt -check
        working-directory: ${{ env.TF_ROOT }}
        continue-on-error: true

      - name: Create Terraform Plugin Cache Dir
        run: mkdir -p $TF_PLUGIN_CACHE_DIR

      - name: Cache Terraform
        uses: actions/cache@v3
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ matrix['terraform-versions'] }}-${{ hashFiles('**/*.tf') }}

      - name: Terraform Init - ${{ matrix['terraform-versions'] }}
        run: terraform init
        working-directory: ${{ env.TF_ROOT }}

      - name: Terraform Validate - ${{ matrix['terraform-versions'] }}
        if: ${{ matrix['terraform-versions'] == 'latest' }}
        run: terraform validate -no-color
        working-directory: ${{ env.TF_ROOT }}
        continue-on-error: true
      
      - name: Terraform Validate - ${{ matrix['terraform-versions'] }}
        if: ${{ matrix['terraform-versions'] != 'latest' }}
        run: terraform validate -no-color
        working-directory: ${{ env.TF_ROOT }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: Check for terraform-docs
        uses: terraform-docs/gh-actions@main
        with:
          working-dir: ${{ TF_ROOT }}
          config-file: .terraform-docs.yml
          fail-on-diff: "true"

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for changelog entry"
        uses: brettcannon/check-for-changed-files@v1.1.1
        with:
          file-pattern: |
            modules/test/.changes/unreleased/*.yaml
            modules/test/CHANGELOG.md
          skip-label: "skip changelog"
          failure-message: "Missing a changelog file in ${file-pattern}; please add one or apply the ${skip-label} label to the pull request"