name: Module
on:
  pull_request:
    branches:
      - "main"
    types:
      - "opened"
      - "reopened"
      - "synchronize"
      - "labeled"
      - "unlabeled"
    paths:
      - "modules/test/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.6

      - name: Terraform fmt -check
        run: |
          terraform fmt -recursive -check | while IFS= read -r filename; do
            if [[ -f "$filename" ]]; then
              echo "::error file=$filename::invalid formatted file"
            fi
          done
          terraform fmt -recursive -check

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for changelog entry"
        uses: brettcannon/check-for-changed-files@v1.1.1
        with:
          file-pattern: |
            modules/test/.changes/unreleased/*.yaml
            modules/test/CHANGELOG.md
          skip-label: "skip changelog"
          failure-message: "Missing a changelog file in ${file-pattern}; please add one or apply the ${skip-label} label to the pull request"